version: '3.8'

services:
  app:
    build: .
    container_name: nestjs-api
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - db
    restart: always

  db:
    image: postgres:13
    container_name: postgres-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=backend_db
    ports:
      - '5435:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
